### ISSUE TITLE
No input validation for money in add new goal

### ISSUE THREAD

**Issue by Pawat-Sarnchawanakit** [MoneyMap-Project/MoneyMap#99]
There seems to be no input validation for baht here
![image](https://github.com/user-attachments/assets/fd29d0ad-85b8-4780-8eac-f3d1a051941a)

Which is unlike here where there is input validation for baht
![image](https://github.com/user-attachments/assets/8ea1a40c-50e9-40c2-825b-c1667389fa0f)

**Comment by colarrbear** [comment]
May I ask which OS and browser do you use to test?

**Comment by colarrbear** [comment]
We think we have already handle this potential-to-be bug. Also cross check in Window OS too since majority of our crew use MacOS with Arc/Chrome. But not sure why in your OS along with your browser doesn't work as expected. Have you disabled Javascript in your browser?

![image](https://github.com/user-attachments/assets/f06129bf-71c9-4f94-8550-bcc645b0eabb)
![image](https://github.com/user-attachments/assets/4a3a7dd1-500a-43f1-8db5-cb795842f9f5)

We would appreciate if you explain in more details.

**Comment by Pawat-Sarnchawanakit** [comment]
I use Windows 11 Firefox browser, Javascript isn't disabled
This is in https://moneymap-thr8.onrender.com/goals/add
I also notice when I type stuff in the input, errors are spammed in console as shown here:
![image](https://github.com/user-attachments/assets/20035791-7258-4b10-b4df-a8901d9674dc)

**Comment by JaofourthsOhappy** [comment]
Fixed. On branch fix-bug-bounty1
